name: Docker Image Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Docker image
        run: |
          docker build -t cosmos_rl:latest .
